site_name: Prospectory
site_url: https://www.prospectory.ai
theme:
  name: material
  logo: assets/logo-light.png
  palette: 
    - scheme: prospectory
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css